### ISSUE TITLE
Cannot include secret when creating Webhook

### ISSUE THREAD

**Issue by Kavishankar** [jbogarin/go-cisco-spark#2]
struct WebhookRequest needs a secret field to be able to create secure webhooks.

**Comment by jbogarin** [comment]
You are absolutely right. I changed that in the new SDK (renamed to go-cisco-webex-teams). Please go to this repo [go-cisco-webex-teams](https://github.com/jbogarin/go-cisco-webex-teams), you can see that [here](https://github.com/jbogarin/go-cisco-webex-teams/blob/master/sdk/webhooks_api.go#L23)
